### ISSUE TITLE
Make planets not just one color but a gradient of colors see line 583 in script.js

### ISSUE THREAD

**Issue by lovbackan** [lovbackan/The-useless-web-assignment#2]

**Comment by lovbackan** [comment]
@AndersonCeci Noticed a bug now, when u press on a planet the planet is black, so the gradient does not seem to carry over there :) I can fix this if you dont want to :)

**Comment by AndersonCeci** [comment]
> @AndersonCeci Noticed a bug now, when u press on a planet the planet is black, so the gradient does not seem to carry over there :) I can fix this if you dont want to :)

Yea I noticed that too, you can go ahead and fix it
