### ISSUE TITLE
If you find any implementation idéas or code improvements feel free to fix, implement or just write a comment

### ISSUE THREAD

**Issue by lovbackan** [lovbackan/The-useless-web-assignment#3]

**Comment by AndersonCeci** [comment]
What if we put the `planetNames`, `galaxyNames`, `lifeKingdoms`, `countryList` on separate files and keep the `script.js` file more clean?

**Comment by lovbackan** [comment]
> What if we put the `planetNames`, `galaxyNames`, `lifeKingdoms`, `countryList` on separate files and keep the `script.js` file more clean?

That is a great idéa, feel free to do it if you want! :)

**Comment by AndersonCeci** [comment]
> > What if we put the `planetNames`, `galaxyNames`, `lifeKingdoms`, `countryList` on separate files and keep the `script.js` file more clean?
> 
> That is a great idéa, feel free to do it if you want! :)

do you want me to delete the existing list or just comment them out?

**Comment by lovbackan** [comment]
> > > What if we put the `planetNames`, `galaxyNames`, `lifeKingdoms`, `countryList` on separate files and keep the `script.js` file more clean?
> > 
> > 
> > That is a great idéa, feel free to do it if you want! :)
> 
> do you want me to delete the existing list or just comment them out?

Sorry for slow reply, you can delete them :)
