### ISSUE TITLE
Give two buttons cursor pointers

### ISSUE THREAD

**Issue by lovbackan** [lovbackan/The-useless-web-assignment#4]
Hey I would like someone to give the two buttons in the right corner "Generate system" & "Show rotation" pointer cursors.

**Comment by AndersonCeci** [comment]
Hey can u assign me on this one, I'm glad to help on this one

**Comment by lovbackan** [comment]
> Hey can u assign me on this one, I'm glad to help on this one

Absolutely, glad to have your help :)

**Comment by AndersonCeci** [comment]
Thank you I'll start to work on this one now

**Comment by lovbackan** [comment]
Thanks for your contribution @AndersonCeci! Have a great day, feel free to work on any other issues in the repo if you want :)

**Comment by AndersonCeci** [comment]
Yep will do thank you
